### ISSUE TITLE
component property based on node ?

### ISSUE THREAD

**Issue by revskill10** [GatsbyCentral/gatsby-awesome-pagination#11]
In my case, i want to render the component based on `templateKey` field of markdown file.
```js
component: path.resolve(
          `src/templates/${String(edge.node.frontmatter.templateKey)}.js`
        ),
```
Is there any option for `component` to be a function of the `edge` ?
Thanks you very much.

**Comment by chmac** [comment]
@revskill10 This is not currently an option. I saw this approach on another site where there was a typo in the markdown template name which caused the whole app to crash. It was not immediately obvious where the issue came from. I wouldn't recommend this approach, it seems like mixing two things in the markdown to me.

You're welcome to fork the package and add this. It should be an easy fix. You can also use the local plugins folder in Gatsby if you don't want to publish on npm, etc. We're not currently open to adding this feature in the main plugin.
