### ISSUE TITLE
Additional context

### ISSUE THREAD

**Issue by silvenon** [GatsbyCentral/gatsby-awesome-pagination#5]
What do you think about adding an option for additional context? In my case I have tagged posts, so when I click on a tag I want to display only those posts, but still paginated. Current API doesn't seem to allow adding additional context, like tag name.

I can submit a PR if you want this.

**Comment by chmac** [comment]
Thanks for reaching out.

I've been thinking about the very same thing. It definitely makes sense to have an API to pass a base `context` object to the resulting `createPage()` calls.

Would you imagine the `paginate()` function takes a new option called `context` and that gets extended with our pagination specific context fields?

**Comment by silvenon** [comment]
Yeah, exactly that. Maybe also later a breaking change where all pagination context gets placed inside the `pagination` key. That way there's only one key that you shouldn't use in the new `context` option.

**Comment by chmac** [comment]
@silvenon At some point I had implemented the `context.foo` key pattern. I found it was really difficult to then use those keys in my GraphQL queries. That's also why I ended up going with just `$skip` and `$limit`, because they made more sense in the GraphQL query. What do you think?

I'll implement the additional `context` option. 👍

**Comment by silvenon** [comment]
Yeah, I didn't even think about that 😅 In any case, for the time being a feature where we could extend the context would be nice. ✨

**Comment by chmac** [comment]
Published as `0.2.0`.
