### ISSUE TITLE
Incorrect NextPagePath and PreviousPagePath When Using "/" As The Path Prefix

### ISSUE THREAD

**Issue by ryanwiemer** [GatsbyCentral/gatsby-awesome-pagination#7]
## Description Of Issue
* I am not currently using a path prefix. Since that is a required filed I used "/". This works as expected with the exception of the `nextPagePath` and `previousPagePath` in the pageContext. (see screenshot below)

<img width="860" alt="screen shot 2018-09-20 at 3 11 49 pm" src="https://user-images.githubusercontent.com/5171579/45849964-fb56bb80-bce8-11e8-8fc6-24c2b7049e45.png">

## Expected Result
The README should provide clearer instructions on how to properly use the plugin when there is no path prefix. This may require adjusting the logic to either make that field optional and have default behavior or to correct the issue shown here.

**Comment by chmac** [comment]
Oooh, interesting. I looked into how Gatsby handles pages like `/foo` vs `/foo/`. I can call `createPage()` twice, with and without the trailing slash. They will be treated as separate pages by Gatsby, but only one of them will be rendered. The "winning" page will be rendered at both `/foo` and `/foo/`.

Anyway, I added some logic to test for a single `/` as the `pathPrefix` and generate proper `path` values. Released it as version 0.3.1 and hopefully your issue is fixed.

Thanks for reporting @ryanwiemer, really appreciate the feedback.
